import React from 'react'
import "./Contact.css"

export const Contact = () => {
  return (
    <div>
      <section className='contact-section'> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span> 
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <div className="contact">
        <div className="contact-content">
          <div className="contact-header">
            <h2>Contact Us!</h2>
          </div>
          <div className="contact-form">
            <div className="det-input">
            <i>Full Name:</i>
            <input type="text" required />
            </div>
            <div className='det-input'> 
            <i>Email:</i> 
              <input type='email' required /> 
            </div> 
            <div className="det-input">
              <textarea name="" id="" cols="30" rows="5"
              placeholder='Input Your text'>

              </textarea>
            </div>
            <div className="det-submit"> 
              <input type="submit" value="Submit" /> 
            </div>
          </div>
        </div>
      </div>
      </section>
    </div>
  )
}
